wandb_version: 1

env:
  desc: null
  value: OpenCabinetDrawer-v1-base_pd_joint_vel_arm_pd_ee_delta_pose
_wandb:
  desc: null
  value:
    code_path: code/run_maniskill/sac.py
    python_version: 3.7.16
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700086508.178593
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.7.16
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
